[tox]
env_list = lint, type, test

[testenv:lint]
deps = .[dev]
commands =
    ruff check fath_cuan/ tests/
    ruff format --check fath_cuan/ tests/

[testenv:type]
deps = .[dev]
commands =
    mypy fath_cuan/

[testenv:test]
deps = .[dev]
commands =
    pytest tests/ -v
